#!/bin/sh

#===============================================================================
# chapter-extract
# extract chapters from a video or audo file and save as a csv file
#===============================================================================

# dependencies:
# ffprobe awk

#===============================================================================
# script usage
#===============================================================================

usage () {
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
extract chapters from a video or audo file and save as a csv file
$(basename "$0") -i input -o output"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check the number of arguments passed to the script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check the options passed to the script
#===============================================================================

while getopts ':i:o:h' opt
do
  case ${opt} in
     i) input="${OPTARG}";;
     h) usage;;
     o) output="${OPTARG}";;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# variables
#===============================================================================

# get the input file name
input_nopath="${input##*/}"
input_name="${input_nopath%.*}"

# output file name
output_default="${input_name}-chapters.txt"


#===============================================================================
# sexagesimal function
#===============================================================================

extract () {
ffprobe -v panic -hide_banner \
-show_chapters -sexagesimal -of csv \
-i input.mp4 \
| awk -F "," '{
          time = $5
          chapter = $NF
          if (time ~ /:/) {
            split(time, t, ".")
            sexagesimal = t[1]
          }
          printf("%s,%s\n"), sexagesimal, chapter
}' > "${output:=${output_default}}"
}


#===============================================================================
# run function
#===============================================================================

extract
