#!/bin/sh

#===============================================================================
# ebu-meter
# ffplay ebu meter
#===============================================================================

# dependencies:
# ffplay

#===============================================================================
# script usage
#===============================================================================

usage()
{
[ -z "${1}" ] || echo "! ${1}"
echo "\
# ffplay ebu meter

$(basename "$0") -i input.(mp4|mkv|mov|m4v|webm|aac|m4a|wav|mp3) -t (00)"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check the number of arguments passed to the script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check the options passed to the script
#===============================================================================

# getopts check and validate options
while getopts ':i:t:h' opt
do
  case ${opt} in
     i) infile="${OPTARG}";;
     t) target="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# variables
#===============================================================================

# default target level
target_default='16'


#===============================================================================
# functions
#===============================================================================

# ebu function
ebu () {
    ffplay -hide_banner \
    -f lavfi -i \
    "amovie=${infile},
    ebur128=video=1:
    meter=18:
    dualmono=true:
    target=-${target:=${target_default}}:
    size=1280x720 [out0][out1]"
}

# run the ebu function
ebu "${infile}"
