#!/bin/sh

#===============================================================================
# overlay-clip
# overlay one video clip on top of another video clip
#===============================================================================

# dependencies:
# ffmpeg ffprobe cut 

#===============================================================================
# script usage
#===============================================================================

usage()
{
# if argument passed to function echo it
[ -z "${1}" ] || echo "! ${1}"
# display help
echo "\
# overlay one video clip on top of another video clip

$(basename "$0") -i input.(mp4|mkv|mov|m4v) -v input.(mp4|mkv|mov|m4v) -p [0-999] -o output.mp4
-i input.(mp4|mkv|mov|m4v) : bottom video
-v input.(mp4|mkv|mov|m4v) : overlay video
-p [0-999]                 : time to overlay the video
-o output.mp4              : optional argument # if option not provided defaults to input-name-overlay-date-time"
exit 2
}


#===============================================================================
# error messages
#===============================================================================

INVALID_OPT_ERR='Invalid option:'
REQ_ARG_ERR='requires an argument'
WRONG_ARGS_ERR='wrong number of arguments passed to script'


#===============================================================================
# check number of arguments passed to the script
#===============================================================================

[ $# -gt 0 ] || usage "${WRONG_ARGS_ERR}"


#===============================================================================
# getopts check the options passed to the script
#===============================================================================

while getopts ':i:v:p:o:h' opt
do
  case ${opt} in
     i) video="${OPTARG}";;
     v) overlay="${OPTARG}";;
     p) position="${OPTARG}";;
     o) outfile="${OPTARG}";;
     h) usage;;
     \?) usage "${INVALID_OPT_ERR} ${OPTARG}" 1>&2;;
     :) usage "${INVALID_OPT_ERR} ${OPTARG} ${REQ_ARG_ERR}" 1>&2;;
  esac
done
shift $((OPTIND-1))


#===============================================================================
# variables
#===============================================================================

# video name extension and overlay video extensions
video_nopath="${video##*/}"
video_name="${video_nopath%.*}"

# defaults for variables if not defined
outfile_default="${video_name}-overlay-$(date +"%Y-%m-%d-%H-%M-%S").mp4"


#===============================================================================
# functions
#===============================================================================

# overlay video function
overlay_video () {
  ffmpeg \
  -hide_banner \
  -stats -v panic \
  -i "${video}" \
  -i "${overlay}" \
  -filter_complex \
  "[0:0]setpts=PTS-STARTPTS[firstclip];
   [1:0]setpts=PTS+${position}/TB[secondclip];
   [firstclip][secondclip]overlay=enable='between(t\,${position},${dp})'[ov]" \
  -map "[ov]" -map 0:1 \
  -pix_fmt yuv420p \
  -c:a copy -c:v libx264 -crf 18 \
  -movflags +faststart \
  -f mp4 \
  "${outfile:=${outfile_default}}"
}

# get overlay videos duration with ffprobe
duration="$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "${overlay}" | cut -d\. -f1)"

# postion + duration
dp="$((position+duration))"

# run the overlay_video function
overlay_video "${video}" "${overlay}"
